%% Based on canonical data version 1.1.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/prime-factors/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(prime_factors_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_no_factors_test'() ->
    ?assertEqual(lists:sort([]),
		 lists:sort(prime_factors:factors(1))).

'2_prime_number_test'() ->
    ?assertEqual(lists:sort([2]),
		 lists:sort(prime_factors:factors(2))).

'3_square_of_a_prime_test'() ->
    ?assertEqual(lists:sort([3, 3]),
		 lists:sort(prime_factors:factors(9))).

'4_cube_of_a_prime_test'() ->
    ?assertEqual(lists:sort([2, 2, 2]),
		 lists:sort(prime_factors:factors(8))).

'5_product_of_primes_and_non_primes_test'() ->
    ?assertEqual(lists:sort([2, 2, 3]),
		 lists:sort(prime_factors:factors(12))).

'6_product_of_primes_test'() ->
    ?assertEqual(lists:sort([5, 17, 23, 461]),
		 lists:sort(prime_factors:factors(901255))).

'7_factors_include_a_large_prime_test'() ->
    ?assertEqual(lists:sort([11, 9539, 894119]),
		 lists:sort(prime_factors:factors(93819012551))).

'8_factors_of_a_negative_number_throw_error_test'() ->
    ?assertMatch({error, invalid_argument}, prime_factors:factors(-2)).

'9_factors_of_zero_throw_error_test'() ->
    ?assertMatch({error, invalid_argument}, prime_factors:factors(0)).